### ISSUE TITLE
Modified row color too bright

### ISSUE THREAD

**Issue by LunarTwilight** [wallysonn/dbgate-plugin-wg-theme-dark#1]
The modified row color is set to `--theme-bg-gold`, which this theme sets to `yellow`, which is way too bright compared to the rest of the theme, and makes the rest of the row unreadable due to the text color being white. Perhaps `#4c4c0c` or etc could be used instead?

https://github.com/wallysonn/dbgate-plugin-wg-theme-dark/blob/02cfe403f4386e002d40e5bf20a2e330ddf330cd/src/index.js#L22

**Comment by wallysonn** [comment]
> A cor da linha modificada é definida para , que este tema define , que é muito brilhante em comparação com o resto do tema, e torna o resto da linha ilegível devido à cor do texto ser branco. Talvez ou etc poderia ser usado em vez disso?`--theme-bg-gold``yellow``#4c4c0c`
> 
> https://github.com/wallysonn/dbgate-plugin-wg-theme-dark/blob/02cfe403f4386e002d40e5bf20a2e330ddf330cd/src/index.js#L22

Ok. Nice observation. I'm sending the correction with the suggested color!

**Comment by LunarTwilight** [comment]
ah nice, thanks!
